# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloWorld < Formula
  desc "Say Hello World - a test package"
  homepage "https://github.com/joshbeard/testing-packaging"
  version "0.11.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://get.jbeard.dev/pkg/0.11.5/hello-world_0.11.5_darwin_amd64.tar.gz"
      sha256 "0f6a9e658c7e8aeac7494c9534eaa063419ffc3dc53841dd395d93380b359696"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.arm?
      url "https://get.jbeard.dev/pkg/0.11.5/hello-world_0.11.5_darwin_arm64.tar.gz"
      sha256 "c9efaaec744a04e19922330f9e39e5e0177ea405d73c4808662087f4003b3c3c"

      def install
        bin.install "hello-world"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://get.jbeard.dev/pkg/0.11.5/hello-world_0.11.5_linux_arm.tar.gz"
      sha256 "3330892dfb6ba876bf749e265bd588cf05d7a3e3dd65d34dc6553ded05da0a6c"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.jbeard.dev/pkg/0.11.5/hello-world_0.11.5_linux_arm64.tar.gz"
      sha256 "f1edd2bad7578d4c5fcb76c47dafadc3b9601a97272230544f088e41474d4ee6"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.intel?
      url "https://get.jbeard.dev/pkg/0.11.5/hello-world_0.11.5_linux_amd64.tar.gz"
      sha256 "eae51520687a55ab9c8ca779b52972a7b3db0e2294b560c982b1628834249e65"

      def install
        bin.install "hello-world"
      end
    end
  end

  test do
    system "#{bin}/hello-world --version"
  end
end
