# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloWorld < Formula
  desc "Say Hello World - a test package"
  homepage "https://github.com/joshbeard/testing-packaging"
  version "0.11.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://get.jbeard.dev/pkg/0.11.7/hello-world_0.11.7_darwin_arm64.tar.gz"
      sha256 "d042fd7cbe2a6f841a90ff6961a7ebdb8b92edc614e7682fa2181ee355eb9a72"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.intel?
      url "https://get.jbeard.dev/pkg/0.11.7/hello-world_0.11.7_darwin_amd64.tar.gz"
      sha256 "bc11934f0267a33b2476e47146528459c8a5c3cca393be3a1614e456e5794462"

      def install
        bin.install "hello-world"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://get.jbeard.dev/pkg/0.11.7/hello-world_0.11.7_linux_amd64.tar.gz"
      sha256 "56ef73c3c99fd6a6097c3b6cfe1681a40e3b6a0a97be3c48b8401e137db96574"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://get.jbeard.dev/pkg/0.11.7/hello-world_0.11.7_linux_arm.tar.gz"
      sha256 "b2cb5de8e2f83a16b0dea2d7db1c1afeae0a8bcbf60936394f32ac65230beb26"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.jbeard.dev/pkg/0.11.7/hello-world_0.11.7_linux_arm64.tar.gz"
      sha256 "af94a7ccada9810fe700519eec2c7e46988ccc86e7928af02d659cc5cbf8c93e"

      def install
        bin.install "hello-world"
      end
    end
  end

  test do
    system "#{bin}/hello-world --version"
  end
end
